# https://github.com/rubenv/sql-migrate#readme
boulder_sa:
  dialect: mysql
  datasource: root@tcp(boulder-proxysql:6033)/boulder_sa?parseTime=true
  dir: boulder_sa

incidents_sa:
  dialect: mysql
  datasource: root@tcp(boulder-proxysql:6033)/incidents_sa?parseTime=true
  dir: incidents_sa
