address: 127.0.0.1:9090
issuer-domain: letsencrypt.org
dns-resolver: 127.0.0.1:8053
dns-timeout: 10s
statsd-server: localhost:8125
statsd-prefix: boulder
certificate-path: test/grpc-creds/server.pem
key-path: test/grpc-creds/key.pem
client-issuer-path: test/grpc-creds/ca.der