debug-addr: 127.0.0.1:8011

dns-resolver: 127.0.0.1:8053
dns-timeout: 10s

statsd-server: 127.0.0.1:8125
statsd-prefix: boulder

grpc:
  address: boulder:9090
  server-certificate-path: test/grpc-creds/boulder-server/cert.pem
  server-key-path: test/grpc-creds/boulder-server/key.pem
  client-issuer-path: test/grpc-creds/minica.pem
  client-whitelist:
    - boulder
